### ISSUE TITLE
version clarification

### ISSUE THREAD

**Issue by dfurber** [ultraleap/TouchFree-Current#2]
TouchFree 1.0 was released in October, and 1.1 in January. The commit dates suggest this is 1.0. Is it possible to have it updated to 1.1?

**Comment by MattGrayUL** [comment]
You are correct, the current version on this repository is 1.0.

I will upload 1.1 to this repository in the coming days and will let you know when it is available. (I need to rename some scripts similar to the commit history you can see)

For some extra information, the changes for 1.1 are specifically tailored towards allowing 'Above Facing User' camera orientations that are available in the Tracking v5 Developer Preview. It features no other significant changes than this.

We are also intending on significantly changing the back-end of TouchFree in the coming months to make use of our [ScreenControl](https://github.com/ultraleap/ScreenControl) repository. This is likely to impact anything you may work on with the current TouchFree repository.

It would be great to know what your plans are when using this repository, either reply to this issue or feel free to send us some details to support@ultraleap.com and we can see if there is any advice or guidance that we can provide?

**Comment by dfurber** [comment]
So... TouchFree is great. But as a UI, touch free kiosk works more like a mouse than a touchscreen. There is a cursor that you move around, and push to click. TouchFree is great for showing the cursor and handling the "air tap" clicks. But the deceptively titled "send hover events" actually sends touchstart and touchend events, which have nothing to do with hovering, but function more like "click started" and "click ended" events. My end goal is to fire actual hover events, such as mouseEnter and mouseLeave, simply in order to improve the user experience.

Using LeapJS and React, I've built a custom event handler system that fires custom events for hovering and clicking, and the elements that listen for these events respond accordingly. I made a crude system to translating fingertip world position to screen x,y position. Eric Johanson pointed me to this repository so I could replicate the math that you use to translate world position to screen position. But from looking at it, the plane/raycast/convert operation in VirtualScreen.cs is the tip of an iceberg of transformations. It makes me wonder if TouchFree could also publish an event that simply tells the x,y position of the cursor. I could then hook that into my custom event handler.

**Comment by MattGrayUL** [comment]
So, what you're describing as your ideal solution here is exactly what [ScreenControl](https://github.com/ultraleap/ScreenControl) is designed to solve. Unfortunately it's not released yet but it won't be too long!

ScreenControl is a Service-Client solution and we are developing dedicated Web and Unity Clients. This will allow you to integrate directly into your applications and send your own events (as well as take advantage of the context of your application for cursor snapping and modification). Although not recommended, you could explore that repository to understand our plans and how that might fit in with your application. It would be great to know if you have any feedback!

If you can't wait and wanted to try to make your own build of TouchFree that sends the events that you want, you can modify the 'VirtualTouchInjector.cs' we use to send Windows events here: [TouchFree/Assets/Plugins/TouchInjection/VirtualTouchInjector.cs ](https://github.com/ultraleap/TouchFree/blob/86650a84e8181e1f8ae381fcf2748b1426f32050/TouchFree/Assets/Plugins/TouchInjection/VirtualTouchInjector.cs#L58).

I hope that is helpful. I also am just [awaiting approval](https://github.com/ultraleap/TouchFree/pull/3) from a team member to move the TouchFree 1.1.0 changes onto the Main branch, so you can be as up-to-date as possible.

**Comment by dfurber** [comment]
I like ideal solutions :)

Does it feel like "won't be too long" is on the order of days, weeks, or months?

**Comment by MattGrayUL** [comment]
Unfortunately it's definitely months for an official full release.

We are currently rolling out an Early Access Program which provides a workable version of ScreenControl but comes with some caveats:

- We do not recommend or support commercial use of the Early Access version
- The 'Service' currently runs as a Windows Application (and must run in the background). (this is intended to change and run as a Windows Service by release)
- Some features may change
- Not all areas are well documented

If this is something you would like to take part in, let me know and I can put you in touch with the right people :)

**Comment by dfurber** [comment]
I'm glad to take part in it. The museum for which the kiosks are intended won't open until October.

**Comment by MattGrayUL** [comment]
Great, I'll grab your details from Eric and pass them onto the right people 😄
